### ISSUE TITLE
Tracking missing documentation

### ISSUE THREAD

**Issue by mkurz** [schaloner/deadbolt-2-java#89]
### General
- [ ] Replace occurences of `F.Promise` in the docs. See #27

### Since version `2.6.3`
- [ ] There is a [`DefaultSubject`](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/models/DefaultSubject.java) class that can be used. See pull request #44

### Since version `2.6.4`
- [ ] **`deadbolt.java.cache-before-auth-check=[true | false (default) ]`**
Caches the result of `deadboltHandler.beforeAuthCheck(...)` for the current request (similar to `deadbolt.java.cache-user`). Also see https://github.com/schaloner/deadbolt-2-java/pull/48#issuecomment-339015564
- [ ] **Constraint modes**
`deadbolt.java.constraint-mode` can be `PROCESS_FIRST_CONSTRAINT_ONLY` (the default, backward compatible), `AND` (*all* constraint annotations of the current action composition chain have to be successful) or `OR` (only *one* constraint annotation of the current action composition chain has to be successful) See tests added in #83 for examples
- [ ] **`@Pattern`: added `mode` attribute (can be `AND` or `OR`) + `value` attribute takes an array now**
Exampe see #88

### Starting with (still unreleased) version `2.7`
(after all the open [`[2.7]` pull requests](https://github.com/schaloner/deadbolt-2-java/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%5B2.7%5D) have been merged)
- [ ] Reflect in docs that `DeadboltHandler.beforeAuthCheck(Http.Context context, Optional<String> content)` also gets `content` passed now
- [ ] Constraint annotations are now `@Repeatable` (actually works with version 2.6.4 and Play 2.6.11 already, however we shouldn't mention it before deadbolt 2.7 comes out so people try to use it with lets say Play 2.6.8). Example see #70
- [ ] `@Deferrable` will be removed in 2.7 - remove it from the docs
